[package]
name = "classes_v0"
version = "0.1.0"
authors = ["Oscar <oscar@merlinjobs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
